version: '3'
services:
  cars:
    container_name: cars
    build:
      context: cars
      dockerfile: Dockerfile
    ports:
      - "19999:9999"
    volumes:
      - /data/cars
    networks:
      - sell-network
  offers:
    container_name: offers
    build:
      context: offers
      dockerfile: Dockerfile
    ports:
      - "18888:8888"
    volumes:
      - /data/offers
    networks:
      - sell-network
networks:
    sell-network:
        driver: bridge
